# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\atulk\OneDrive\Desktop\python Bootcamp\pyqt\basic-calci.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1123, 866)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(410, 39, 241, 41))
        self.label.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";color:rgb(255, 85, 0)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(200, 150, 171, 31))
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";color:rgb(0, 0, 255)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(200, 240, 201, 41))
        self.label_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";color:rgb(0, 0, 255)")
        self.label_3.setObjectName("label_3")
        self.txtfirstnumber = QtWidgets.QLineEdit(Form)
        self.txtfirstnumber.setGeometry(QtCore.QRect(420, 151, 201, 41))
        self.txtfirstnumber.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";color:rgb(0, 0, 0)")
        self.txtfirstnumber.setObjectName("txtfirstnumber")
        self.txtsecondnumber = QtWidgets.QLineEdit(Form)
        self.txtsecondnumber.setGeometry(QtCore.QRect(420, 241, 201, 41))
        self.txtsecondnumber.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";color:rgb(0, 0, 0)")
        self.txtsecondnumber.setObjectName("txtsecondnumber")
        self.btnadd = QtWidgets.QPushButton(Form)
        self.btnadd.setGeometry(QtCore.QRect(190, 440, 141, 41))
        self.btnadd.setObjectName("btnadd")
        self.btnsubtract = QtWidgets.QPushButton(Form)
        self.btnsubtract.setGeometry(QtCore.QRect(360, 440, 141, 41))
        self.btnsubtract.setObjectName("btnsubtract")
        self.btnmultiply = QtWidgets.QPushButton(Form)
        self.btnmultiply.setGeometry(QtCore.QRect(520, 440, 141, 41))
        self.btnmultiply.setObjectName("btnmultiply")
        self.btndivide = QtWidgets.QPushButton(Form)
        self.btndivide.setGeometry(QtCore.QRect(680, 440, 141, 41))
        self.btndivide.setObjectName("btndivide")
        self.lblmessage = QtWidgets.QLabel(Form)
        self.lblmessage.setGeometry(QtCore.QRect(390, 720, 231, 51))
        self.lblmessage.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";color:rgb(0, 0, 0)")
        self.lblmessage.setText("")
        self.lblmessage.setObjectName("lblmessage")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(200, 330, 191, 41))
        self.label_4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";color:rgb(0, 0, 255)")
        self.label_4.setObjectName("label_4")
        self.txtthirdnumber = QtWidgets.QLineEdit(Form)
        self.txtthirdnumber.setGeometry(QtCore.QRect(420, 331, 201, 41))
        self.txtthirdnumber.setObjectName("txtthirdnumber")
        self.btnadd.clicked.connect(self.ADD)
        self.btnsubtract.clicked.connect(self.SUBTRACT)
        self.btnmultiply.clicked.connect(self.MUL)
        self.btndivide.clicked.connect(self.DIV)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Basic Calculator"))
        self.label.setText(_translate("Form", "Basic Calculator"))
        self.label_2.setText(_translate("Form", "First Number"))
        self.label_3.setText(_translate("Form", "Second Number"))
        self.btnadd.setText(_translate("Form", "ADD"))
        self.btnsubtract.setText(_translate("Form", "SUBTRACT"))
        self.btnmultiply.setText(_translate("Form", "MULTIPLY"))
        self.btndivide.setText(_translate("Form", "DIVIDE"))
        self.label_4.setText(_translate("Form", "Third Number"))
        
    def ADD(self):
        firstnumber = self.txtfirstnumber.text()
        secondnumber = self.txtsecondnumber.text()
        thirdnumber = self.txtthirdnumber.text()
        result = int(firstnumber) + int(secondnumber) + int(thirdnumber)
        self.lblmessage.setText(str(result))
    
    def SUBTRACT(self):
        firstnumber = self.txtfirstnumber.text()
        secondnumber = self.txtsecondnumber.text()
        thirdnumber = self.txtthirdnumber.text()
        result = int(firstnumber) - int(secondnumber) - int(thirdnumber)
        self.lblmessage.setText(str(result))
                                
    def MUL(self):
        firstnumber = self.txtfirstnumber.text()
        secondnumber = self.txtsecondnumber.text()
        thirdnumber = self.txtthirdnumber.text()
        result = int(firstnumber) * int(secondnumber) * int(thirdnumber)
        self.lblmessage.setText(str(result))
                                
    def DIV(self):
        firstnumber = self.txtfirstnumber.text()
        secondnumber = self.txtsecondnumber.text()
        thirdnumber = self.txtthirdnumber.text()
        result = int(firstnumber) / int(secondnumber) / int(thirdnumber)
        self.lblmessage.setText(str(result))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
